cert-manager: {}

scaleway-certmanager-webhook:
  secret:
    accessKey: ""
    secretKey: ""

defaultWildcard:
  enabled: true
  dnsZone: "example.com"
  ingressNamespace: "ingress-nginx"
  secretName: "default-wildcard-tls"
  issuerRef:
    kind: "ClusterIssuer"
    name: "letsencrypt-dns-prod"

clusterIssuers: []
