cert-manager:
  crds:
    enabled: true
    keep: true
  prometheus:
    enabled: true
    servicemonitor:
      enabled: true

scaleway-certmanager-webhook:
  secret:
    accessKey: ""
    secretKey: ""

defaultWildcard:
  enabled: true
  dnsZone: ""
  ingressNamespace: "ingress-nginx"
  secretName: "default-wildcard-tls"
  issuerRef:
    kind: "ClusterIssuer"
    name: "letsencrypt-dns-prod"

clusterIssuers: []
# - name: letsencrypt-http-staging
#   spec:
#     acme:
#       email: ""
#       server: https://acme-staging-v02.api.letsencrypt.org/directory
#       privateKeySecretRef:
#         name: letsencrypt-http-staging-key
#       solvers:
#       - http01:
#           ingress:
#             serviceType: ClusterIP
#             ingressClassName: nginx
# - name: letsencrypt-http-prod
#   spec:
#     acme:
#       email: ""
#       server: https://acme-v02.api.letsencrypt.org/directory
#       privateKeySecretRef:
#         name: letsencrypt-http-prod-key
#       solvers:
#       - http01:
#           ingress:
#             serviceType: ClusterIP
#             ingressClassName: nginx
# - name: letsencrypt-dns-staging
#   spec:
#     acme:
#       email: ""
#       server: https://acme-staging-v02.api.letsencrypt.org/directory
#       privateKeySecretRef:
#         name: letsencrypt-dns-staging-key
#       solvers:
#       - dns01:
#           webhook:
#             groupName: acme.scaleway.com
#             solverName: scaleway
# - name: letsencrypt-dns-prod
#   spec:
#     acme:
#       email: ""
#       server: https://acme-v02.api.letsencrypt.org/directory
#       privateKeySecretRef:
#         name: letsencrypt-dns-prod-key
#       solvers:
#       - dns01:
#           webhook:
#             groupName: acme.scaleway.com
#             solverName: scaleway

vso:
  vaultAuth:
    default:
      method: "kubernetes"
      mount: "kubernetes"
      kubernetes:
        role: "cert-manager"
        serviceAccount: "default"
  vaultConnection:
    default:
      address: "https://vault.vault-operator-system.svc.cluster.local:8200"
      skipTLSVerify: true
  vaultStaticSecrets:
    scwCreds:
      mount: ""
      path: ""
      type: "kv-v2"
      vaultAuthRef: "cert-manager-vso-default"
      refreshAfter: "1h"
      hmacSecretData: true
      destination:
        name: "scw-creds"
        create: true
        type: "Opaque"
        transformation:
          excludes:
          - ".*"
          templates:
            SCW_ACCESS_KEY:
              text: '{{ get .Secrets "scaleway" | dig "accessKey" "" }}'
            SCW_SECRET_KEY:
              text: '{{ get .Secrets "scaleway" | dig "secretKey" "" }}'
