- name: Reset current vault values
  ansible.builtin.set_fact:
    current_vault_values:

- name: Retrieve current vault secret
  community.hashi_vault.vault_kv2_get:
    url: http://{{ vault.namespace }}-active.{{ vault.namespace }}.svc.cluster.local:8200
    auth_method: token
    token: "{{ vault_core_token }}"
    namespace: secret
    path: "platforms/{{ platform_env.conf.env }}/apps/{{ argocd_app }}"
  register: current_vault_values
  ignore_errors: true

- name: Get current non null values
  ansible.builtin.shell:
    cmd: |
      echo '{
        "old": {{ current_vault_values.secret | default({}) | to_json }},
        "new": {{ vault_values | default({}) | to_json }}
      }' | yq -p=json -o=json -I=0 '.old *n .new'
  register: current_vault_values_combined

- name: Compare vault values
  ansible.utils.fact_diff:
    before: "{{ current_vault_values.secret | default({}) | to_nice_json }}"
    after: "{{ current_vault_values_combined.stdout | from_json | to_nice_json }}"
  register: json_comparison_result

- name: Update vault secret
  community.hashi_vault.vault_kv2_write:
    url: http://{{ vault.namespace }}-active.{{ vault.namespace }}.svc.cluster.local:8200
    auth_method: token
    token: "{{ vault_core_token }}"
    namespace: secret
    path: "platforms/{{ platform_env.conf.env }}/apps/{{ argocd_app }}"
    data: "{{ current_vault_values_combined.stdout | from_json }}"
  when: json_comparison_result.changed
