- name: Create cert directory
  delegate_to: localhost
  ansible.builtin.file:
    path: /tmp/homelab/{{ item.username }}/.crt
    state: directory
    mode: "0755"

- name: Generate an OpenSSL private key
  delegate_to: localhost
  community.crypto.openssl_privatekey:
    path: /tmp/homelab/{{ item.username }}/.crt/kube.key
    size: 2048

- name: Generate an OpenSSL Certificate Signing Request
  delegate_to: localhost
  community.crypto.openssl_csr:
    path: /tmp/homelab/{{ item.username }}/.crt/kube.csr
    privatekey_path: /tmp/homelab/{{ item.username }}/.crt/kube.key
    common_name: "{{ item.username }}"

- name: Create k8s CertificateRequest
  delegate_to: localhost
  kubernetes.core.k8s:
    state: present
    template: certificate-signing-request.yml.j2

- name: Approve k8s CertificateRequest
  delegate_to: localhost
  ansible.builtin.command: kubectl certificate approve user-request-{{ item.username }}
  changed_when: true

- name: Deploy rbac
  delegate_to: localhost
  kubernetes.core.k8s:
    state: present
    template: rbac-admin.yml.j2

- name: Find user certificate
  delegate_to: localhost
  kubernetes.core.k8s_info:
    kind: CertificateSigningRequest
    name: user-request-{{ item.username }}
  register: k3s_admin_user_certificate

- name: Fetch user certificate
  delegate_to: localhost
  ansible.builtin.copy:
    content: "{{ k3s_admin_user_certificate.resources[0].status.certificate | b64decode }}"
    dest: /tmp/homelab/{{ item.username }}/.crt/kube.crt
    mode: "0644"

- name: Create kube directory
  delegate_to: localhost
  ansible.builtin.file:
    path: /tmp/homelab/{{ item.username }}/.kube
    state: directory
    owner: "{{ item.username }}"
    group: "{{ item.username }}"
    mode: "0755"
  become: true

- name: Create kubeconfig
  delegate_to: localhost
  ansible.builtin.template:
    src: kubeconfig.yml.j2
    dest: /tmp/homelab/{{ item.username }}/.kube/config
    owner: "{{ item.username }}"
    group: "{{ item.username }}"
    mode: "0644"
