{{- if .Values.avp.enabled }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: vault-plugin-secret
data:
  VAULT_ADDR: {{.Values.avp.vaultAddr | b64enc }}
  VAULT_TOKEN: {{ .Values.avp.vaultToken | b64enc  }}
  AVP_TYPE: {{ .Values.avp.type | b64enc }}
  AVP_AUTH_TYPE: {{ .Values.avp.authType | b64enc }}
{{- end }}
