argo-cd:
  enabled: true
  # fullnameOverride: argo-cd-system-argocd
  configs:
    secret:
      argocdServerAdminPassword: "$2a$10$xak1yhpxkZPvqIpY5YeClOIvAn2Bnso88vOQtxxrjFqYHin9qSuoK"
  server:
    ingress:
      hostname: "gitops.core.ohmlab.fr"
      extraTls:
      - hosts:
        - "gitops.core.ohmlab.fr"
        secretName: "gitops.core.ohmlab.fr-tls"
