- name: Remove pihole when disabled
  when: not pihole.enabled
  block:
    - name: Create pihole service dir
      ansible.builtin.file:
        path: "/services/pihole"
        state: directory
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: "0775"

    - name: Copy docker-compose file
      ansible.builtin.template:
        src: "docker-compose.yml.j2"
        dest: "/services/pihole/docker-compose.yml"
        mode: "0644"

    - name: Launch pihole
      community.docker.docker_compose_v2:
        state: absent
        project_src: "/services/pihole"
        files:
          - "docker-compose.yml"

- name: Deploy pihole when enabled
  when: pihole.enabled
  block:
    - name: Set pihole password
      ansible.builtin.set_fact:
        gateway_pihole_password: "{{ lookup('ansible.builtin.password', '/dev/null', length=24, chars=['ascii_letters', 'digits']) }}"

    - name: Fetch pihole password
      delegate_to: localhost
      become: false
      ansible.builtin.shell:
        cmd: |
          yq -i '.pihole.password = "{{ gateway_pihole_password }}"' ./inventory/group_vars/gateway.yml
      when: pihole.password == ''
      changed_when: pihole.password == ''

    - name: Create pihole service dir
      ansible.builtin.file:
        path: "/services/pihole"
        state: directory
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: "0775"

    - name: Copy docker-compose file
      ansible.builtin.template:
        src: "docker-compose.yml.j2"
        dest: "/services/pihole/docker-compose.yml"
        mode: "0644"

    - name: Launch pihole
      community.docker.docker_compose_v2:
        state: present
        project_src: "/services/pihole"
        files:
          - "docker-compose.yml"
